## Exercise 6.1

Starting to familiarize and clean the california census tract data set. The data set contains information on pollutants and demogrpahics on census tract areas in CA, with scores that take into account the factors provided.

In [55]:
# Import Libraries
import pandas as pd
import numpy as np
import os

In [56]:
# Set path

path = r'C:\Users\Jenna\Desktop\Data Course\Part 6\Raw Data'

In [57]:
# Import data

df = pd.read_csv(os.path.join(path, 'CA_data.csv'), index_col = False)

In [58]:
# check shape

df.shape

(8035, 57)

In [59]:
# check head
pd.options.display.max_columns = None
df.head()

,Census Tract,Total Population,California County,ZIP,Nearby City \n(to help approximate location only),Longitude,Latitude,CES 3.0 Score,CES 3.0 Percentile,CES 3.0 \nPercentile Range,SB 535 Disadvantaged Community,Ozone,Ozone Pctl,PM2.5,PM2.5 Pctl,Diesel PM,Diesel PM Pctl,Drinking Water,Drinking Water Pctl,Pesticides,Pesticides Pctl,Tox. Release,Tox. Release Pctl,Traffic,Traffic Pctl,Cleanup Sites,Cleanup Sites Pctl,Groundwater Threats,Groundwater Threats Pctl,Haz. Waste,Haz. Waste Pctl,Imp. Water Bodies,Imp. Water Bodies Pctl,Solid Waste,Solid Waste Pctl,Pollution Burden,Pollution Burden Score,Pollution Burden Pctl,Asthma,Asthma Pctl,Low Birth Weight,Low Birth Weight Pctl,Cardiovascular Disease,Cardiovascular Disease Pctl,Education,Education Pctl,Linguistic Isolation,Linguistic Isolation Pctl,Poverty,Poverty Pctl,Unemployment,Unemployment Pctl,Housing Burden,Housing Burden Pctl,Pop. Char.,Pop. Char. Score,Pop. Char. Pctl
0,6019001100,3174,Fresno,93706,Fresno,-119.781696,36.709695,94.09,100.00,95-100% (highest scores),Yes,0.065,98.18,15.40,97.22,48.524,95.54,681.20,80.92,2.75,47.82,18551.957190,97.46,909.14,62.98,80.5,98.67,45.75,89.85,0.795,84.32,0,0.00,21.75,97.81,79.96,9.85,99.95,131.64,97.67,7.44,93.84,14.13,96.31,53.3,95.76,16.2,77.51,76.3,97.12,17.6,91.72,26.0,79.40,92.12,9.55,99.70
1,6071001600,6133,San Bernardino,91761,Ontario,-117.618013,34.057780,90.68,99.99,95-100% (highest scores),Yes,0.062,91.10,13.31,93.64,38.556,92.12,904.66,96.11,1.37,41.34,7494.236622,89.05,782.26,55.66,66.2,97.68,36.00,85.57,1.250,88.77,5,55.01,12.00,92.17,81.19,10.00,100.00,60.66,69.78,7.04,90.85,12.94,92.66,53.3,95.76,33.4,96.25,72.5,94.63,12.3,71.82,34.1,93.75,87.44,9.07,98.11
2,6019000200,3167,Fresno,93706,Fresno,-119.805504,36.735491,85.97,99.97,95-100% (highest scores),Yes,0.062,91.10,15.40,97.22,47.445,95.42,681.20,80.92,3.03,48.75,12454.948410,95.42,576.52,39.00,22.0,85.13,30.25,81.93,0.200,60.50,0,0.00,2.50,57.18,71.16,8.76,99.00,142.12,98.33,10.16,99.78,14.96,97.67,42.3,89.06,16.7,78.39,86.8,99.56,16.1,87.98,40.1,97.85,94.58,9.81,99.99
3,6077000801,6692,San Joaquin,95203,Stockton,-121.314524,37.940517,82.49,99.96,95-100% (highest scores),Yes,0.046,53.02,12.54,84.02,24.117,73.52,278.76,29.11,12.93,60.56,2387.782922,69.97,1305.01,78.29,50.1,96.10,132.10,98.41,0.795,84.32,19,98.63,27.00,99.10,74.48,9.17,99.59,142.17,98.34,6.23,80.65,14.72,97.17,40.8,87.52,15.3,75.14,61.3,85.57,19.6,94.97,21.1,63.54,86.70,8.99,97.72
4,6019001500,2206,Fresno,93725,Fresno,-119.717843,36.681600,82.03,99.95,95-100% (highest scores),Yes,0.065,98.18,15.40,97.22,18.846,58.22,1000.24,98.64,3518.41,95.15,21790.706720,98.15,435.16,24.30,60.0,97.15,54.20,92.09,13.100,99.70,0,0.00,50.80,99.91,80.20,9.88,99.99,90.48,89.54,4.50,38.92,12.82,92.36,45.1,91.13,14.7,73.72,66.4,90.23,18.6,93.65,28.1,83.98,80.08,8.30,92.76

## 1. First Step: 

I Think that for the purpose of my analysis, I will drop the percentile and scored columns and just focus on the values, I will save the smaller dataset under a different name in case I decided to use the percentiles later. I will also drop unneeded information

In [62]:
# drop column
col_to_drop = [
    'CES 3.0 Score',
    'SB 535 Disadvantaged Community',
    'CES 3.0 Percentile',
    'CES 3.0 \nPercentile Range',
    'Ozone Pctl',
    'PM2.5 Pctl',
    'Diesel PM Pctl',
    'Drinking Water Pctl',
    'Pesticides Pctl',
    'Tox. Release Pctl',
    'Traffic Pctl',
    'Cleanup Sites Pctl',
    'Groundwater Threats Pctl',
    'Haz. Waste Pctl',
    'Imp. Water Bodies Pctl',
    'Solid Waste Pctl',
    'Pollution Burden Pctl',
    'Asthma Pctl',
    'Low Birth Weight Pctl',
    'Cardiovascular Disease Pctl',
    'Education Pctl',
    'Linguistic Isolation Pctl',
    'Poverty Pctl',
    'Unemployment Pctl',
    'Housing Burden Pctl',
    'Pop. Char. Pctl',
    'Nearby City \n(to help approximate location only)',
    'Pop. Char.',
    'Pop. Char. Score',
    'Pollution Burden',
   'Pollution Burden Score'
]

df = df.drop(columns= col_to_drop)
df.head()

,Census Tract,Total Population,California County,ZIP,Longitude,Latitude,Ozone,PM2.5,Diesel PM,Drinking Water,Pesticides,Tox. Release,Traffic,Cleanup Sites,Groundwater Threats,Haz. Waste,Imp. Water Bodies,Solid Waste,Asthma,Low Birth Weight,Cardiovascular Disease,Education,Linguistic Isolation,Poverty,Unemployment,Housing Burden
0,6019001100,3174,Fresno,93706,-119.781696,36.709695,0.065,15.40,48.524,681.20,2.75,18551.957190,909.14,80.5,45.75,0.795,0,21.75,131.64,7.44,14.13,53.3,16.2,76.3,17.6,26.0
1,6071001600,6133,San Bernardino,91761,-117.618013,34.057780,0.062,13.31,38.556,904.66,1.37,7494.236622,782.26,66.2,36.00,1.250,5,12.00,60.66,7.04,12.94,53.3,33.4,72.5,12.3,34.1
2,6019000200,3167,Fresno,93706,-119.805504,36.735491,0.062,15.40,47.445,681.20,3.03,12454.948410,576.52,22.0,30.25,0.200,0,2.50,142.12,10.16,14.96,42.3,16.7,86.8,16.1,40.1
3,6077000801,6692,San Joaquin,95203,-121.314524,37.940517,0.046,12.54,24.117,278.76,12.93,2387.782922,1305.01,50.1,132.10,0.795,19,27.00,142.17,6.23,14.72,40.8,15.3,61.3,19.6,21.1
4,6019001500,2206,Fresno,93725,-119.717843,36.681600,0.065,15.40,18.846,1000.24,3518.41,21790.706720,435.16,60.0,54.20,13.100,0,50.80,90.48,4.50,12.82,45.1,14.7,66.4,18.6,28.1

In [63]:
# Check the new shape of my dataframe

df.shape

(8035, 26)

In [64]:
df.describe()

,Census Tract,Total Population,ZIP,Longitude,Latitude,Ozone,PM2.5,Diesel PM,Drinking Water,Pesticides,Tox. Release,Traffic,Cleanup Sites,Groundwater Threats,Haz. Waste,Imp. Water Bodies,Solid Waste,Asthma,Low Birth Weight,Cardiovascular Disease,Education,Linguistic Isolation,Poverty,Unemployment,Housing Burden
count,8.035000e+03,8035.000000,8035.000000,8035.000000,8035.000000,8035.000000,8016.000000,8035.000000,8017.000000,8035.000000,8035.000000,7979.000000,8035.000000,8035.000000,8035.000000,8035.000000,8035.000000,8035.000000,7813.000000,8035.000000,7939.000000,7793.000000,7956.000000,7880.000000,7878.000000
mean,6.054896e+09,4636.459988,92836.574611,-119.409318,35.495893,0.047430,10.377904,19.196064,472.372294,313.973556,3182.713557,943.043646,8.370541,15.700759,0.453356,3.279029,2.232738,51.977813,4.976329,8.265890,19.121779,10.417862,36.386790,10.214327,19.327913
std,2.652280e+07,1972.587602,3445.177594,1.976336,2.086016,0.010244,2.598074,16.993880,249.331571,2775.125375,12556.830160,907.358215,16.532104,36.354482,1.470877,4.516895,4.706866,30.552249,1.551352,2.971099,15.952094,9.982732,20.316885,5.136715,8.734286
min,6.001400e+09,0.000000,32.000000,-124.297889,32.547376,0.026000,1.651081,0.021000,6.920000,0.000000,0.000000,22.410000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,6.037265e+09,3358.000000,91602.000000,-121.518410,33.924145,0.040000,8.697944,8.812000,249.350000,0.000000,94.797220,442.075000,0.000000,0.200000,0.000000,0.000000,0.000000,29.855000,3.950000,6.080000,6.300000,3.000000,19.200000,6.600000,12.900000
50%,6.059053e+09,4413.000000,92691.000000,-118.429194,34.206624,0.046000,10.370000,16.448000,479.230000,0.000000,474.004778,699.890000,2.000000,5.600000,0.050000,1.000000,0.200000,45.270000,4.920000,7.940000,14.000000,7.400000,33.500000,9.300000,18.000000
75%,6.073016e+09,5656.500000,94558.000000,-117.924814,37.634021,0.055000,12.050000,24.646500,664.070000,0.370000,3474.186429,1190.075000,10.300000,17.800000,0.225000,6.000000,2.250000,65.990000,5.930000,10.040000,28.700000,14.900000,51.500000,12.900000,24.400000
max,6.115041e+09,37452.000000,96161.000000,-114.306484,41.946648,0.068000,19.600000,253.731000,1245.650000,91316.190000,842751.329300,45687.870000,323.750000,1610.250000,28.695000,34.000000,97.800000,278.830000,14.890000,21.260000,80.000000,72.300000,96.200000,100.000000,67.200000

# 2nd Step: Data Cleaning

Check data types, check for mixed columns

In [65]:
df.dtypes

Census Tract                int64
Total Population            int64
California County          object
ZIP                         int64
Longitude                 float64
Latitude                  float64
Ozone                     float64
PM2.5                     float64
Diesel PM                 float64
Drinking Water            float64
Pesticides                float64
Tox. Release              float64
Traffic                   float64
Cleanup Sites             float64
Groundwater Threats       float64
Haz. Waste                float64
Imp. Water Bodies           int64
Solid Waste               float64
Asthma                    float64
Low Birth Weight          float64
Cardiovascular Disease    float64
Education                 float64
Linguistic Isolation      float64
Poverty                   float64
Unemployment              float64
Housing Burden            float64
dtype: object

In [66]:
# check for mixed columns

for col in df.columns.tolist():
    weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
    if len (df[weird]) > 0:
        print (col)

## Check for missing data

In [67]:
# check for missing data 
df.isnull().sum()

Census Tract                0
Total Population            0
California County           0
ZIP                         0
Longitude                   0
Latitude                    0
Ozone                       0
PM2.5                      19
Diesel PM                   0
Drinking Water             18
Pesticides                  0
Tox. Release                0
Traffic                    56
Cleanup Sites               0
Groundwater Threats         0
Haz. Waste                  0
Imp. Water Bodies           0
Solid Waste                 0
Asthma                      0
Low Birth Weight          222
Cardiovascular Disease      0
Education                  96
Linguistic Isolation      242
Poverty                    79
Unemployment              155
Housing Burden            157
dtype: int64

## Some data is missing or not applicable, I will leave it unchanged for now

## Check for duplicate data

In [68]:
# find duplicates in the data

df_dups = df[df.duplicated()]

In [69]:
df_dups

Empty DataFrame
Columns: [Census Tract, Total Population, California County, ZIP, Longitude, Latitude, Ozone, PM2.5, Diesel PM, Drinking Water, Pesticides, Tox. Release, Traffic, Cleanup Sites, Groundwater Threats, Haz. Waste, Imp. Water Bodies, Solid Waste, Asthma, Low Birth Weight, Cardiovascular Disease, Education, Linguistic Isolation, Poverty, Unemployment, Housing Burden]
Index: []

# Export data

In [70]:
df.to_csv(os.path.join(path, 'NEW_CA_data.csv'))